// <auto-generated />
namespace MVC_WebCargoRequestHandler.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class currentUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(currentUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201809051308237_currentUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
